### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by banjaminicc** [HolyWu/vs-basicvsrpp#28]
```
      pybind.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
      pybind.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
      build\lib.win-amd64-cpython-310\mmcv\_ext.cp310-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
 ```
      when attempting to install through pip
      any ideas?

**Comment by HolyWu** [comment]
https://github.com/open-mmlab/mmcv#install-mmcv-full

**Comment by banjaminicc** [comment]
a random question
is it possible to use trt with this implementation considering its abominal  speed?

**Comment by banjaminicc** [comment]
Also
```
Python exception: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\torch\lib\cudnn_cnn_train64_8.dll" or one of its dependencies.

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
  File "Colour conversion.vpy", line 6, in <module>
    from vsbasicvsrpp import BasicVSRPP
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vsbasicvsrpp\__init__.py", line 4, in <module>
    import mmcv
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\mmcv\utils\__init__.py", line 22, in <module>
    import torch
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\torch\lib\cudnn_cnn_train64_8.dll" or one of its dependencies.
```
I have made sure that the .dll in fact exists at the path

**Comment by banjaminicc** [comment]
Also
I'm facing a new error
```
load checkpoint from local path: C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vsbasicvsrpp\spynet.pth
load checkpoint from local path: C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vsbasicvsrpp\basicvsr_plusplus_ntire_decompress_track1.pth
C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vspreview\main\window.py", line 574, in switch_output
    self.switch_frame(self.current_output.last_showed_frame)
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vspreview\main\window.py", line 538, in switch_frame
    self.current_output.render_frame(frame, output_colorspace=self.display_profile)
  File "C:\Users\icckl\AppData\Roaming\Python\Python310\site-packages\vspreview\core\types\video.py", line 329, in render_frame
    vs_frame = vs_frame or self.prepared.clip.get_frame(frame.value)
  File "src\cython\vapoursynth.pyx", line 1866, in vapoursynth.VideoNode.get_frame
vapoursynth.Error: modulated_deformable_im2col_impl: implementation for device cuda:0 not found.
```
