### ISSUE TITLE
OpenMim aliyunsdkcore dependency

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#37]
trying to run:
````
python -m pip install -U openmim
mim install "mmcv>=2.0.0"
python -m pip install -U vsbasicvsrpp
python -m vsbasicvsrpp
````
to install BasicVSR++ in a portable Vapoursynth setup (R64 with Python3.11), but the first call ends with:
```
python -m pip install -U openmim
Collecting openmim
  Obtaining dependency information for openmim from https://files.pythonhosted.org/packages/00/b3/95531cee452028869d0e08974561f83e9c256c98f62c7a45a51893a61c54/openmim-0.3.9-py2.py3-none-any.whl.metadata
  Using cached openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Collecting Click (from openmim)
  Obtaining dependency information for Click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: colorama in f:\hybrid\64bit\vapoursynth\lib\site-packages (from openmim) (0.4.6)
Collecting model-index (from openmim)
  Using cached model_index-0.1.11-py3-none-any.whl (34 kB)
Collecting opendatalab (from openmim)
  Obtaining dependency information for opendatalab from https://files.pythonhosted.org/packages/10/82/28fa3a91b7c4852fbad9ad32c7b49e4b1e212ab7ccf7296736da0935070d/opendatalab-0.0.10-py3-none-any.whl.metadata
  Using cached opendatalab-0.0.10-py3-none-any.whl.metadata (6.4 kB)
Collecting pandas (from openmim)
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/2d/5e/9213ea10ac473e2437dc2cb17323ddc0999997e2713d6a0b683b10773994/pandas-2.1.1-cp311-cp311-win_amd64.whl.metadata
  Using cached pandas-2.1.1-cp311-cp311-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: pip>=19.3 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from openmim) (23.2.1)
Requirement already satisfied: requests in f:\hybrid\64bit\vapoursynth\lib\site-packages (from openmim) (2.31.0)
Requirement already satisfied: rich in f:\hybrid\64bit\vapoursynth\lib\site-packages (from openmim) (13.6.0)
Collecting tabulate (from openmim)
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: pyyaml in f:\hybrid\64bit\vapoursynth\lib\site-packages (from model-index->openmim) (6.0.1)
Collecting markdown (from model-index->openmim)
  Obtaining dependency information for markdown from https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl.metadata
  Using cached Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)
Collecting ordered-set (from model-index->openmim)
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting pycryptodome (from opendatalab->openmim)
  Obtaining dependency information for pycryptodome from https://files.pythonhosted.org/packages/87/c4/c979db0914a23541d62c9e4b5e8a30f56a78c6dec8677db6a5327d306be5/pycryptodome-3.19.0-cp35-abi3-win_amd64.whl.metadata
  Using cached pycryptodome-3.19.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: tqdm in f:\hybrid\64bit\vapoursynth\lib\site-packages (from opendatalab->openmim) (4.66.1)
Collecting openxlab (from opendatalab->openmim)
  Obtaining dependency information for openxlab from https://files.pythonhosted.org/packages/4a/ac/61a17d0b5fc704c268f83591efb326fafda76e7d2bad3b2bec60fe1ebe54/openxlab-0.0.26-py3-none-any.whl.metadata
  Using cached openxlab-0.0.26-py3-none-any.whl.metadata (3.7 kB)
Collecting pywin32 (from opendatalab->openmim)
  Using cached pywin32-306-cp311-cp311-win_amd64.whl (9.2 MB)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from requests->openmim) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from requests->openmim) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from requests->openmim) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from requests->openmim) (2023.7.22)
Requirement already satisfied: numpy>=1.23.2 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from pandas->openmim) (1.26.0)
Collecting python-dateutil>=2.8.2 (from pandas->openmim)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas->openmim)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas->openmim)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from rich->openmim) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from rich->openmim) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from markdown-it-py>=2.2.0->rich->openmim) (0.1.2)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->openmim)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting oss2~=2.17.0 (from openxlab->opendatalab->openmim)
  Using cached oss2-2.17.0.tar.gz (259 kB)
  Preparing metadata (setup.py) ... done
Collecting requests (from openmim)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting rich (from openmim)
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/fc/1e/482e5eec0b89b593e81d78f819a9412849814e22225842b598908e7ac560/rich-13.4.2-py3-none-any.whl.metadata
  Using cached rich-13.4.2-py3-none-any.whl.metadata (18 kB)
Collecting setuptools~=60.2.0 (from openxlab->opendatalab->openmim)
  Using cached setuptools-60.2.0-py3-none-any.whl (953 kB)
Collecting tqdm (from opendatalab->openmim)
  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/c0/ab/bd9ba7f84c509c8b377628bc66696d52623e30c6c0830db3c78748eec4b4/tqdm-4.65.2-py3-none-any.whl.metadata
  Using cached tqdm-4.65.2-py3-none-any.whl.metadata (56 kB)
Collecting urllib3<1.27,>=1.21.1 (from requests->openmim)
  Obtaining dependency information for urllib3<1.27,>=1.21.1 from https://files.pythonhosted.org/packages/48/fe/a5c6cc46e9fe9171d7ecf0f33ee7aae14642f8d74baa7af4d7840f9358be/urllib3-1.26.17-py2.py3-none-any.whl.metadata
  Using cached urllib3-1.26.17-py2.py3-none-any.whl.metadata (48 kB)
Collecting crcmod>=1.7 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached crcmod-1.7.tar.gz (89 kB)
  Preparing metadata (setup.py) ... done
Collecting aliyun-python-sdk-kms>=2.4.1 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Obtaining dependency information for aliyun-python-sdk-kms>=2.4.1 from https://files.pythonhosted.org/packages/3d/ea/d88e08bfc4a0aee0111f1f24c98b19107bc6783441e7e944907c77b2243d/aliyun_python_sdk_kms-2.16.2-py2.py3-none-any.whl.metadata
  Using cached aliyun_python_sdk_kms-2.16.2-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.14.0.tar.gz (443 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-t2r9eu4j\aliyun-python-sdk-core_b912f61c599e490b859580d9c77cbbd2\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Over at https://github.com/duangy/aliyunsdkcore I saw they use:
```
pip install aliyun-python-sdk-core-v3
````
but calling:
```
python -m pip install aliyun-python-sdk-core-v3
```
also ended with:
```
Collecting aliyun-python-sdk-core-v3
  Using cached aliyun-python-sdk-core-v3-2.13.33.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-z34bfyjn\aliyun-python-sdk-core-v3_d41c02850b1149618eabccde823a8da3\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

=> Any idea how to fix this?

**Comment by HolyWu** [comment]
Cannot reproduce. Install successfully in a new venv.
```
python -m venv C:\test_openmim
C:\test_openmim\Scripts\activate.bat
python -m pip install -U openmim
```

File an issue at https://github.com/open-mmlab/mim if you still have problems.

**Comment by HolyWu** [comment]
Pre-built package for PyTorch 2.1+cu121 is probably not available. File an issue to MMCV if you really hurry to have it.

**Comment by Selur** [comment]
Thanks for looking at it. I'll wait and see.

**Comment by Selur** [comment]
As a small update:
There is one for PyTorch 2.1+cu121 now: https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv-2.1.0-cp311-cp311-win_amd64.whl
but none for PyTorch 2.1.1+cu121 which is a bummer since https://github.com/HolyWu/vs-ddcolor uses PyTorch 2.1.1 :(

**Comment by HolyWu** [comment]
https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv-2.1.0-cp311-cp311-win_amd64.whl is compatible with 2.1.x, hence that's not an issue.

**Comment by Selur** [comment]
Ah, thanks for the info!
