### ISSUE TITLE
Broken after vsrife update.

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#41]
I updated vsrife:
```
pip install -U packaging setuptools wheel
pip install --pre -U torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu126
pip install --no-deps --pre -U torch_tensorrt --index-url https://download.pytorch.org/whl/nightly/cu126
pip install -U tensorrt-cu12 tensorrt-cu12_bindings tensorrt-cu12_libs --extra-index-url https://pypi.nvidia.com
pip install -U vsrife
python -m vsrife
```
now basicvsrpp fails with:
```
Failed to evaluate the script:
Python exception: DLL load failed while importing _ext: Die angegebene Prozedur wurde nicht gefunden.

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluate
File "J:\tmp\tempPreviewVapoursynthFile13_09_13_002.vpy", line 37, in 
from vsbasicvsrpp import basicvsrpp as BasicVSRPP
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsbasicvsrpp\__init__.py", line 13, in 
from .basicvsr_plusplus_net import BasicVSRPlusPlusNet
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsbasicvsrpp\basicvsr_plusplus_net.py", line 5, in 
from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\mmcv\ops\__init__.py", line 3, in 
from .active_rotated_filter import active_rotated_filter
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in 
ext_module = ext_loader.load_ext(
^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
ext = importlib.import_module('mmcv.' + name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "importlib\__init__.py", line 90, in import_module
ImportError: DLL load failed while importing _ext: Die angegebene Prozedur wurde nicht gefunden.
```
:(

**Comment by Selur** [comment]
as a workaround I installed vsrife directly from the whl and not updating the dependencies, at least this doesn't break vsbasicvsrpp and vsdeoldify.
